MODEL:
  TYPE: vit
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: True
    USE_RPB: False
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: False
DATA:
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.44
  THROW_RATIO: 0.26
TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-4
  WARMUP_LR: 5e-7
  WEIGHT_DECAY: 0.05
  AMT_START_EPOCH: 40
PRINT_FREQ: 100
SAVE_FREQ: 20
TAG: simmim_pretrain
